const app = document.querySelector('#app');
const roles = ['client', 'trainer', 'admin'];
let selectedRole = 'client';
let runtimeStep = 'warmup';
let selectedWorkoutType = 'weights';
let selectedMuscleMode = 'single';
let selectedMuscles = ['Legs'];
let timerSeconds = 1200;
let timerRunning = false;
let timerId;
let completedSets = 0;
let toastTimer;
let lastCompletion = { type: 'weights', calories: 0, fatGrams: 0 };
let trainingSlot = 'Morning · 06:00–08:00';
let slotNotification = 'Notified Maya Singh';

const profile = { name: 'Aisha Khan', weight: '68.4', height: '178', age: '29', goal: 'Muscle gain' };
const roleMeta = {
  client: { label: 'Client', title: 'Your strongest hour starts here.', description: 'A focused training companion, built around the plan your trainer made for you.', accent: 'Today, fully yours.' },
  trainer: { label: 'Trainer', title: 'Make every client feel seen.', description: 'One calm command center for plans, progress, and the moments that move clients forward.', accent: 'Coach with clarity.' },
  admin: { label: 'Admin', title: 'The quiet power behind the platform.', description: 'See the health of your operation at a glance and keep every trainer moving.', accent: 'Operations, elevated.' }
};
const dayPlans = [
  { day: 'MON', type: 'weights', title: 'Lower body strength', detail: 'Single muscle · Legs', color: 'lime' },
  { day: 'TUE', type: 'cardio', title: 'Cardio rotation', detail: '3 sets · 62 min', color: 'blue' },
  { day: 'WED', type: 'recovery', title: 'Mobility recovery', detail: 'Stretch · 20 min', color: 'paper' },
  { day: 'THU', type: 'hiit', title: 'Athletic HIIT', detail: '4 rounds · 18 min', color: 'coral' },
  { day: 'FRI', type: 'weights', title: 'Upper body strength', detail: 'Double muscle · Back + biceps', color: 'blue' },
  { day: 'SAT', type: 'cardio', title: 'Endurance cardio', detail: 'Intervals · 40 min', color: 'lime' },
  { day: 'SUN', type: 'rest', title: 'Rest day', detail: 'Recovery matters', color: 'paper' }
];
const workoutData = {
  cardio: { title: 'Cardio rotation', subtitle: '3 sets · guided intensity', demo: 'Treadmill incline walk', cue: 'Tall posture · light grip · steady breathing', muscles: 'Heart and full-body conditioning', equipment: 'Treadmill, cross trainer, air bike', steps: ['Set a pace you can sustain with controlled breathing.', 'Keep a light grip and let your lower body drive the motion.', 'Finish each interval with a smooth transition, not a sprint.', 'Record effort from 1 to 10 after the set.'], tips: ['Keep posture tall.', 'Use the handrails only for balance.', 'Stop if you feel sharp pain or dizziness.'], blocks: ['Cross trainer · 15:00', 'Treadmill · 15:00', 'Air bike · 15:00', 'Spin bike · 15:00', 'Ski machine · 02:00'] },
  weights: { title: 'Lower body strength', subtitle: 'Heavy to light progression', demo: 'Goblet squat', cue: 'Chest lifted · knees track over toes · controlled descent', muscles: 'Quadriceps, glutes, hamstrings', equipment: 'Dumbbell or kettlebell', steps: ['Stand with feet just outside hip width and hold the weight at your chest.', 'Brace your core, sit your hips down, and keep your knees tracking over toes.', 'Pause at a comfortable depth, then drive through the whole foot.', 'Lower the weight or stop if form breaks down.'], tips: ['Lead with control, not momentum.', 'Keep heels grounded.', 'Choose a load that leaves two good reps in reserve.'], blocks: ['Goblet squat · 3 × 8', 'Romanian deadlift · 3 × 10', 'Reverse lunge · 3 × 12', 'Leg press · 3 × 10', 'Standing calf raise · 3 × 15'] },
  hiit: { title: 'Athletic HIIT', subtitle: '4 rounds · 30 / 30 intervals', demo: 'Battle rope waves', cue: 'Soft knees · fast hands · breathe continuously', blocks: ['Battle rope · 30 sec work', 'Step-up · 40 sec work', 'Rest · 60 sec'] }
};

function shell(content, action = '') {
  app.innerHTML = `<div class="app-shell"><header class="topbar"><div class="brand"><span class="brand-mark">E</span> ELEVATE</div><div class="top-actions"><span class="eyebrow">${action || 'Personal training, refined'}</span>${action ? '<button class="ghost" data-action="logout">Sign out</button>' : ''}</div></header><main class="main">${content}</main></div>`;
  document.querySelector('[data-action="logout"]')?.addEventListener('click', renderLogin);
}
function metric(label, value, note) { return `<div class="metric"><span>${label}</span><strong>${value}</strong><span>${note}</span></div>`; }
function metricCard(kind, label, value, note) { return `<button class="metric metric-button" data-insight="${kind}"><span>${label}</span><strong>${value}</strong><span>${note}</span><b>View trend →</b></button>`; }
function avatar(name) { return `<div class="avatar">${name.split(' ').map(word => word[0]).join('').slice(0, 2)}</div>`; }
function bmi() { const value = Number(profile.weight) / ((Number(profile.height) / 100) ** 2); return Number.isFinite(value) ? value.toFixed(1) : '--'; }
function showToast(message) { document.querySelector('.toast')?.remove(); const toast = document.createElement('div'); toast.className = 'toast'; toast.textContent = message; document.body.appendChild(toast); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.remove(), 2600); }
function calculateCompletion(type) { const values = { cardio: { calories: 612, fatGrams: 68 }, weights: { calories: 438, fatGrams: 49 }, hiit: { calories: 286, fatGrams: 32 } }; return values[type] || values.weights; }
function renderCompletionSummary() {
  const metrics = lastCompletion;
  shell(`<section class="completion-screen"><div class="confetti" aria-hidden="true">${Array.from({ length: 110 }, (_, index) => `<i style="--i:${index}"></i>`).join('')}</div><div class="festival-rays" aria-hidden="true"></div><div class="completion-content"><div class="completion-badge">✦</div><div class="eyebrow">Session complete</div><h1>That one counts.</h1><p class="subtle">Your ${workoutData[metrics.type].title.toLowerCase()} is logged. Recovery is ready when you are.</p><div class="completion-metrics"><div><strong>${metrics.calories}</strong><span>estimated kcal burned</span></div><div><strong>${metrics.fatGrams}g</strong><span>estimated fat equivalent</span></div><div><strong>${completedSets}</strong><span>blocks completed</span></div></div><p class="fine-print">Estimates are based on workout type and duration, not a medical measurement.</p><button class="primary" data-action="return-dashboard">Return to dashboard</button></div></section>`, 'Workout complete');
  document.querySelector('.app-shell').classList.add('completion-app');
  document.querySelector('[data-action="return-dashboard"]').addEventListener('click', () => { completedSets = 0; timerSeconds = 1200; renderClient(); });
}
function renderLogin() {
  shell(`<section class="login-layout"><div class="visual"><div><div class="eyebrow" style="color:#d5f34a">${roleMeta[selectedRole].accent}</div><h1>${roleMeta[selectedRole].title}</h1><p>${roleMeta[selectedRole].description}</p></div><div class="visual-foot"><div class="stat-chip"><strong>24/7</strong><span>trainer support</span></div><div class="stat-chip"><strong>01</strong><span>beautiful plan</span></div></div></div><div class="auth-card"><div class="eyebrow">${roleMeta[selectedRole].label} access</div><h2>Welcome back.</h2><p class="subtle">Sign in to continue your Elevate experience.</p><div class="role-tabs">${roles.map(role => `<button class="role-tab ${role === selectedRole ? 'active' : ''}" data-role="${role}">${roleMeta[role].label}</button>`).join('')}</div><form id="login-form"><div class="form-field"><label for="email">Email address</label><input id="email" type="email" value="${selectedRole}@elevate.demo" required /></div><div class="form-field"><label for="password">Password</label><input id="password" type="password" value="elevate-demo" required /></div><button class="primary full" type="submit">Continue securely</button></form>${selectedRole === 'admin' ? '<button class="text-link" data-action="admin-reset-login">Admin password reset</button>' : ''}<p class="demo-note">Demo mode is active. Use the prefilled credentials to explore this role.</p></div></section>`);
  document.querySelectorAll('[data-role]').forEach(button => button.addEventListener('click', () => { selectedRole = button.dataset.role; renderLogin(); }));
  document.querySelector('#login-form').addEventListener('submit', event => { event.preventDefault(); renderDashboard(selectedRole); });
  document.querySelector('[data-action="admin-reset-login"]')?.addEventListener('click', openAdminResetWithTwoFactor);
}
function openAdminReset() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Admin only</div><h3>Reset administrator password</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="admin-reset-form"><div class="form-field"><label>Admin email</label><input type="email" value="admin@elevate.demo" required /></div><div class="form-field"><label>New temporary password</label><input type="password" value="Elevate-2026!" required /></div><button class="primary full" type="submit">Reset password securely</button></form></div></div>`); bindClose(); document.querySelector('#admin-reset-form').addEventListener('submit', event => { event.preventDefault(); event.currentTarget.closest('.modal-backdrop').remove(); showToast('Admin password reset link issued'); }); }
function profileForm() {
  return `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" aria-modal="true" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Client profile</div><h3>Update your metrics</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="profile-form"><div class="photo-upload"><div class="avatar">AK</div><div><strong>Profile picture</strong><small>Upload a clear photo for your trainer</small></div><button type="button" class="ghost">Choose photo</button></div><div class="form-grid"><div class="form-field"><label>Name</label><input name="name" value="${profile.name}" /></div><div class="form-field"><label>Age</label><input name="age" type="number" value="${profile.age}" /></div><div class="form-field"><label>Weight (kg)</label><input name="weight" type="number" step="0.1" value="${profile.weight}" /></div><div class="form-field"><label>Height (cm)</label><input name="height" type="number" value="${profile.height}" /></div></div><label class="form-field"><label>Fitness goal</label><select name="goal"><option ${profile.goal === 'Fat loss' ? 'selected' : ''}>Fat loss</option><option ${profile.goal === 'Muscle gain' ? 'selected' : ''}>Muscle gain</option><option ${profile.goal === 'Shredding' ? 'selected' : ''}>Shredding</option></select></label><button class="primary full" type="submit">Save metrics</button></form></div></div>`;
}
function renderClient() {
  const today = dayPlans[0];
  shell(`<section class="dashboard"><div class="dashboard-head"><div><div class="eyebrow">Monday, 14 September 2026</div><h1>Good morning, ${profile.name.split(' ')[0]}.</h1></div><div class="dashboard-actions"><button class="ghost" data-action="edit-profile">Update profile</button><button class="primary" data-action="start-workout">Start workout</button></div></div><div class="grid-4">${metricCard('weight', 'Current weight', `${profile.weight} kg`, '-4.6 kg since start')}${metricCard('bmi', 'BMI', bmi(), 'calculated from your metrics')}${metricCard('sessions', 'Sessions complete', '18 / 24', '75% this month')}${metricCard('streak', 'Streak', '06 days', 'your best yet')}</div><div class="content-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Today · ${today.type.toUpperCase()}</div><h3>${today.title}</h3><p class="subtle">${today.detail}</p></div><span class="pill">Ready</span></div><div class="workout-list"><button class="workout-row workout-button" data-workout-detail="warmup"><div class="workout-icon">01</div><div><strong>Warm-up flow</strong><small>20 min · guided timer</small></div><span class="status">Next →</span></button><button class="workout-row workout-button" data-workout-detail="${today.type}"><div class="workout-icon">02</div><div><strong>${today.title}</strong><small>${today.detail}</small></div><span class="status">Assigned →</span></button><button class="workout-row workout-button" data-workout-detail="recovery"><div class="workout-icon">03</div><div><strong>Recovery stretch</strong><small>08 min · guided cues</small></div><span class="status">After →</span></button></div></div><div class="panel"><div class="eyebrow">This month</div><div class="progress-ring"><div class="progress-copy"><strong>72%</strong><span>complete</span></div></div><p class="subtle" style="text-align:center">Three sessions away from your monthly target.</p><button class="ghost full" data-action="view-progress">View full progress</button></div></div><div class="panel schedule-panel"><div class="panel-head"><div><div class="eyebrow">Your week</div><h3>Training schedule</h3></div><span class="subtle">14–20 Sep</span></div><div class="schedule">${dayPlans.map((day, index) => `<button class="schedule-day ${index === 0 ? 'active' : ''}" data-schedule-day="${index}"><span>${day.day}</span><strong>${14 + index}</strong><small>${day.type === 'weights' ? 'Strength' : day.title.split(' ')[0]}</small></button>`).join('')}</div><div class="schedule-detail" id="schedule-detail"><strong>${today.title}</strong><span>${today.detail}</span></div></div></section>`, 'Client dashboard');
  document.querySelector('.grid-4').insertAdjacentHTML('beforeend', metricCard('calories', 'Avg calories burned', '438 kcal', 'per completed workout'));
  document.querySelector('.content-grid').insertAdjacentHTML('beforebegin', `<div class="assignment-chip"><span class="avatar">MS</span><span><small>Assigned trainer</small><strong>Maya Singh · Elevate Central</strong></span><label class="slot-control"><small>Training slot</small><select data-client-slot><option ${trainingSlot.startsWith('Morning') ? 'selected' : ''}>Morning · 06:00–08:00</option><option ${trainingSlot.startsWith('Midday') ? 'selected' : ''}>Midday · 12:00–14:00</option><option ${trainingSlot.startsWith('Evening') ? 'selected' : ''}>Evening · 18:00–20:00</option></select></label><button class="whatsapp-button" data-action="whatsapp">Message on WhatsApp</button></div>`);
  document.querySelector('.dashboard-actions').insertAdjacentHTML('beforeend', '<button class="whatsapp-button" data-action="whatsapp">WhatsApp trainer · +91 98765 43210</button>');
  document.querySelectorAll('[data-action="whatsapp"]').forEach(button => button.addEventListener('click', openWhatsApp));
  document.querySelector('[data-client-slot]').addEventListener('change', event => { trainingSlot = event.target.value; slotNotification = 'Notification sent to Maya Singh'; showToast(`${trainingSlot} selected · ${slotNotification}`); });
  document.querySelectorAll('[data-insight]').forEach(card => card.addEventListener('click', () => openClientInsight(card.dataset.insight)));
  document.querySelector('[data-action="start-workout"]').addEventListener('click', () => { selectedWorkoutType = today.type === 'recovery' || today.type === 'rest' ? 'weights' : today.type; runtimeStep = 'warmup'; renderRuntime(); });
  document.querySelector('[data-action="edit-profile"]').addEventListener('click', () => { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', profileForm()); bindProfileModal(); });
  document.querySelector('[data-action="view-progress"]').addEventListener('click', openProgressReport);
  document.querySelectorAll('[data-workout-detail]').forEach(button => button.addEventListener('click', () => { const type = button.dataset.workoutDetail; if (type === 'warmup') { runtimeStep = 'warmup'; renderRuntime(); } else if (type === 'recovery') { runtimeStep = 'recovery'; renderRuntime(); } else { openWorkoutDetail(type); } }));
  document.querySelectorAll('[data-schedule-day]').forEach(button => button.addEventListener('click', () => { const plan = dayPlans[Number(button.dataset.scheduleDay)]; document.querySelectorAll('.schedule-day').forEach(day => day.classList.remove('active')); button.classList.add('active'); document.querySelector('#schedule-detail').innerHTML = `<strong>${plan.title}</strong><span>${plan.detail}</span>`; }));
}
function bindClose() { document.querySelectorAll('[data-action="close-modal"]').forEach(button => button.addEventListener('click', event => { if (event.target === button) button.closest('.modal-backdrop')?.remove(); })); }
function bindProfileModal() { bindClose(); document.querySelector('#profile-form').addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.currentTarget); Object.assign(profile, Object.fromEntries(data)); event.currentTarget.closest('.modal-backdrop').remove(); renderClient(); showToast('Profile metrics updated'); }); }
function openClientInsight(kind) {
  const insights = {
    weight: { eyebrow: 'Body metrics', title: 'Weight journey', copy: 'A steady downward trend with enough energy left for your training.', value: `${profile.weight} kg`, accent: '−4.6 kg', bars: [76, 70, 66, 61, 58, 54, 50] },
    bmi: { eyebrow: 'Body metrics', title: 'BMI snapshot', copy: 'Your current BMI is calculated from the latest profile metrics.', value: bmi(), accent: 'Target range', bars: [43, 49, 55, 61, 66, 70, 73] },
    sessions: { eyebrow: 'Consistency', title: 'Session momentum', copy: 'You are building a reliable rhythm. Keep the next two sessions protected.', value: '18 / 24', accent: '75% complete', bars: [35, 48, 42, 61, 68, 77, 86] },
    streak: { eyebrow: 'Consistency', title: 'Streak energy', copy: 'Six days in a row. Your best streak is becoming your normal.', value: '06 days', accent: 'Personal best', bars: [22, 31, 45, 58, 63, 75, 92] }
  }[kind];
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal insight-modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">${insights.eyebrow}</div><h3>${insights.title}</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="insight-hero"><strong>${insights.value}</strong><span>${insights.accent}</span></div><p class="subtle">${insights.copy}</p><div class="chart-3d" aria-label="Interactive ${insights.title} chart">${insights.bars.map((height, index) => `<button class="chart-bar" style="--bar-height:${height}%" data-chart-bar="${index}" aria-label="Week ${index + 1}: ${height}"><i></i><span>W${index + 1}</span></button>`).join('')}</div><div class="chart-legend"><span>Earlier</span><span>Latest</span></div><button class="primary full" data-action="view-progress-from-insight">Open full progress report</button></div></div>`);
  bindClose();
  document.querySelectorAll('[data-chart-bar]').forEach(bar => bar.addEventListener('click', () => { document.querySelectorAll('.chart-bar').forEach(item => item.classList.remove('active')); bar.classList.add('active'); showToast(`Week ${Number(bar.dataset.chartBar) + 1} selected`); }));
  document.querySelector('[data-action="view-progress-from-insight"]').addEventListener('click', () => { document.querySelector('.modal-backdrop').remove(); openProgressReport(); });
}
function openProgressReport() {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide insight-modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Your journey</div><h3>Progress, in motion</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="progress-report">${metric('Start weight', '73.0 kg', 'baseline')}${metric('Current weight', `${profile.weight} kg`, `${(Number(profile.weight) - 73).toFixed(1)} kg change`)}${metric('BMI', bmi(), 'updated today')}${metric('Completed', '18', 'sessions')}</div><div class="chart-3d large-chart">${[64, 58, 52, 47, 42, 38, 33, 29].map((height, index) => `<div class="chart-bar" style="--bar-height:${height}%"><i></i><span>${index + 1}</span></div>`).join('')}</div><div class="gallery-placeholder"><span>BEFORE<br /><small>73 kg</small></span><span>PROGRESS<br /><small>68.4 kg</small></span><span>NEXT MILESTONE<br /><small>66 kg</small></span></div></div></div>`);
  bindClose();
}
function openWorkoutDetail(type, index = 0) {
  const workout = workoutData[type] || workoutData.weights;
  const block = workout.blocks[index] || workout.blocks[0];
  const guide = workout.steps || ['Follow the demonstration at a controlled pace.', 'Keep your breathing steady throughout the movement.', 'Log your effort once the block is complete.'];
  const tips = workout.tips || ['Use the demonstrated range of motion.', 'Prioritize quality over speed.', 'Stop if form or breathing becomes unsafe.'];
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide insight-modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Workout block ${index + 1} · ${type.toUpperCase()}</div><h3>${block}</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="exercise-profile"><span><b>Target</b>${workout.muscles || 'Full-body conditioning'}</span><span><b>Equipment</b>${workout.equipment || 'Trainer-selected'}</span><span><b>Level</b>Beginner friendly</span></div><div class="demo-visual"><button class="play-button" data-action="play-inline-demo">▶</button><div><span>FORM DEMO · ORIGINAL PLACEHOLDER</span><strong>${workout.demo}</strong><small>${workout.cue}</small></div></div><div class="guide-columns"><div><h4>How to perform</h4><ol>${guide.map(step => `<li>${step}</li>`).join('')}</ol></div><div><h4>Coach tips</h4><ul>${tips.map(tip => `<li>${tip}</li>`).join('')}</ul></div></div><div class="exercise-cues"><strong>Execution focus</strong><span>Watch the demonstration, then log your effort and move at your own pace.</span><label><input type="checkbox" /> I understand the form cues</label></div><button class="primary full" data-action="mark-inline-set">Mark set complete</button></div></div>`);
  bindClose();
  document.querySelector('[data-action="play-inline-demo"]').addEventListener('click', event => { event.currentTarget.textContent = 'Ⅱ'; event.currentTarget.classList.add('playing'); showToast(`${workout.demo} demo playing`); });
  document.querySelector('[data-action="mark-inline-set"]').addEventListener('click', () => { document.querySelector('.modal-backdrop').remove(); showToast(`${block} marked complete`); });
}
function openTrainerMetric(kind) {
  const content = {
    clients: ['Active clients', '24 active clients', '4 new this month', 'Sort by last activity, goal, or adherence.'],
    completion: ['Completion rate', '86%', '+8.4% vs last month', 'The strongest lift is coming from the Monday strength cohort.'],
    attention: ['Needs attention', '07 clients', '2 urgent today', 'Daniel missed a session, Priya added a meal, and Laura needs a plan.'],
    meals: ['Meal logs', '31 awaiting review', '12 added today', 'Review food photos, portions, and leave a nutrition note.']
  }[kind];
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Trainer analytics</div><h3>${content[0]}</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="insight-hero"><strong>${content[1]}</strong><span>${content[2]}</span></div><p class="subtle">${content[3]}</p><div class="trainer-analytics"><div class="analytics-line"><span>Mon</span><i style="--line-value:72%"></i></div><div class="analytics-line"><span>Tue</span><i style="--line-value:84%"></i></div><div class="analytics-line"><span>Wed</span><i style="--line-value:66%"></i></div><div class="analytics-line"><span>Thu</span><i style="--line-value:92%"></i></div></div><button class="primary full" data-action="open-review-from-metric">Open related client reviews</button></div></div>`);
  bindClose();
  document.querySelector('[data-action="open-review-from-metric"]').addEventListener('click', () => { document.querySelector('.modal-backdrop').remove(); openClientReview(content[0], content[3]); });
}
function openWhatsApp() { window.open('https://wa.me/919876543210?text=Hi%20Maya%2C%20I%20need%20help%20with%20my%20training%20session.', '_blank', 'noopener'); }
function openTrainerReviewQueue() {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide queue-modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Maya Singh · 24 assigned clients</div><h3>Review queue</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="slot-select"><label>Client slot</label><select data-roster-slot><option>All assigned clients</option><option>Morning slot · 6 clients</option><option>Afternoon slot · 10 clients</option><option>Evening slot · 8 clients</option></select></div><div class="queue-layout"><div class="queue-list-pane"><div class="toolbar"><button class="filter active-filter" data-roster-filter="all">All clients · 24</button><button class="filter" data-roster-filter="attention">Needs attention · 7</button><button class="filter" data-roster-filter="completed">Completed today · 9</button></div><div class="roster-list">${[['Aisha Khan', 'Lower body strength', '5 / 5 blocks', 'completed'], ['Daniel Reed', 'Cardio rotation', '4 / 5 blocks', 'attention'], ['Priya Shah', 'HIIT', '4 / 4 rounds', 'completed'], ['Laura Kim', 'No workout yet', 'Needs check-in', 'attention'], ['Omar Patel', 'Upper body strength', '3 / 5 blocks', 'attention']].map(client => `<button class="roster-item" data-roster-status="${client[3]}" data-roster-client="${client[0]}"><span class="avatar">${client[0].split(' ').map(word => word[0]).join('')}</span><span><strong>${client[0]}</strong><small>${client[1]}</small></span><b>${client[2]}</b><span class="pill ${client[3] === 'attention' ? 'coral' : ''}">${client[3] === 'attention' ? 'Review' : 'On track'}</span></button>`).join('')}</div></div><div class="queue-detail" data-queue-detail><div class="queue-empty"><strong>Select a client</strong><span>The list stays open while you review each client.</span></div></div></div></div></div>`);
  bindClose();
  document.querySelector('[data-roster-slot]').addEventListener('change', event => showToast(`${event.target.value} selected`));
  document.querySelectorAll('[data-roster-filter]').forEach(filter => filter.addEventListener('click', () => { document.querySelectorAll('[data-roster-filter]').forEach(item => item.classList.remove('active-filter')); filter.classList.add('active-filter'); const mode = filter.dataset.rosterFilter; document.querySelectorAll('[data-roster-status]').forEach(row => { row.style.display = mode === 'all' || row.dataset.rosterStatus === mode ? 'grid' : 'none'; }); }));
  document.querySelectorAll('[data-roster-client]').forEach(row => row.addEventListener('click', () => openQueueClientDetail(row.dataset.rosterClient, row.dataset.rosterStatus === 'attention' ? 'Needs attention' : 'Workout review')));
}
function openTrainerReschedule(slot) {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Trainer schedule</div><h3>Reschedule ${slot} slot</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="reschedule-form"><div class="form-field"><label>Client</label><select name="client"><option>Aisha Khan</option><option>Daniel Reed</option><option>Priya Shah</option><option>Laura Kim</option></select></div><div class="form-field"><label>New training time</label><select name="time"><option>Morning · 06:00–08:00</option><option>Midday · 12:00–14:00</option><option>Evening · 18:00–20:00</option></select></div><div class="form-field"><label>Message to client</label><textarea name="message" rows="3">Your trainer moved your session to the selected time. Please confirm that this works for you.</textarea></div><label class="check dark-check"><input type="checkbox" name="notify" checked /> Notify client and update their calendar</label><button class="primary full" type="submit">Save and notify client</button></form></div></div>`); bindClose(); document.querySelector('#reschedule-form').addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.currentTarget); slotNotification = `Updated ${data.get('client')} · notification sent`; event.currentTarget.closest('.modal-backdrop').remove(); renderTrainer(); showToast(slotNotification); });
}
function openQueueClientDetail(name, reason) {
  const detail = document.querySelector('[data-queue-detail]');
  if (!detail) return;
  detail.innerHTML = `<div class="queue-detail-head"><div><div class="eyebrow">${reason}</div><h3>${name}</h3><small>Assigned slot · ${trainingSlot}</small></div><button class="ghost" data-action="queue-back">← Back to list</button></div><div class="review-summary">${metric('Completion', name === 'Daniel Reed' ? '64%' : '92%', 'last 30 days')}${metric('Last session', name === 'Laura Kim' ? 'None' : 'Today', 'trainer review')}${metric('Blocks', name === 'Daniel Reed' ? '4 / 5' : '5 / 5', 'latest workout')}</div><div class="review-section"><div class="panel-head"><div><div class="eyebrow">Workout review</div><h3>Latest activity</h3></div><span class="pill">${name === 'Laura Kim' ? 'Needs plan' : 'Ready'}</span></div><div class="review-workout-row"><span>Lower body strength · 14 Sep</span><strong>${name === 'Daniel Reed' ? '4 / 5' : '5 / 5'} blocks</strong><button class="icon-button" data-action="queue-open-workout">Open</button></div><div class="review-workout-row"><span>Trainer note</span><strong>${name === 'Laura Kim' ? 'Create first plan' : 'No note yet'}</strong><button class="icon-button" data-action="queue-done">Done</button></div></div><div class="queue-detail-actions"><button class="ghost" data-action="queue-select-other">Select another client</button><button class="primary" data-action="queue-done">Mark review done</button></div></div>`;
  document.querySelector('[data-action="queue-back"]').addEventListener('click', () => { detail.innerHTML = '<div class="queue-empty"><strong>Select a client</strong><span>The list stays open while you review each client.</span></div>'; });
  document.querySelector('[data-action="queue-select-other"]').addEventListener('click', () => { detail.innerHTML = '<div class="queue-empty"><strong>Select another client</strong><span>Choose a client from the list on the left.</span></div>'; });
  document.querySelector('[data-action="queue-open-workout"]').addEventListener('click', () => openWorkoutDetail('weights'));
  document.querySelectorAll('[data-action="queue-done"]').forEach(button => button.addEventListener('click', () => { showToast(`${name} review marked done`); detail.innerHTML = '<div class="queue-empty success-empty"><strong>Review complete</strong><span>Select another client from the list.</span></div>'; }));
}
function openAdminManage(account) {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Admin account management</div><h3>Manage ${account}</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="photo-upload"><div class="avatar">${account.split(' ').map(word => word[0]).join('')}</div><div><strong>Profile picture</strong><small>Received · visibility enabled</small></div><button type="button" class="ghost">Replace</button></div><div class="form-field"><label>Assignment slot</label><select><option>Maya Singh · Elevate Central</option><option>Unassigned</option></select></div><div class="form-field"><label>Account status</label><select><option>Active</option><option>Paused</option><option>Suspended</option></select></div><button class="primary full" data-action="save-account-management">Save account changes</button></div></div>`); bindClose(); document.querySelector('[data-action="save-account-management"]').addEventListener('click', () => { document.querySelector('.modal-backdrop').remove(); showToast(`${account} account changes saved`); });
}
function openAdminDelete(account) {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Admin-only destructive action</div><h3>Delete ${account}?</h3></div><button class="ghost" data-action="close-modal">Cancel</button></div><p class="subtle">This revokes login access, removes active assignments, and queues personal data for deletion. The action is written to the audit trail.</p><label class="check dark-check"><input type="checkbox" data-delete-confirm /> I understand this cannot be undone.</label><button class="danger-button full" data-action="confirm-account-delete" disabled>Delete account</button></div></div>`); bindClose(); const confirm = document.querySelector('[data-delete-confirm]'); const deleteButton = document.querySelector('[data-action="confirm-account-delete"]'); confirm.addEventListener('change', () => { deleteButton.disabled = !confirm.checked; }); deleteButton.addEventListener('click', () => { document.querySelector('.modal-backdrop').remove(); showToast(`${account} deletion queued and audit event created`); });
}
function openPlatformActivity(kind) { const details = { workouts: ['Workouts started', '186', 'Most active window: 06:00–09:00', '84% were completed on mobile.'], meals: ['Meal logs uploaded', '94', '12 awaiting trainer review', 'Photo uploads are processing normally.'], response: ['Trainer response rate', '92%', 'Target: 90%', 'Maya Singh’s cohort is at 96% this week.'] }[kind]; document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Platform analytics</div><h3>${details[0]}</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="insight-hero"><strong>${details[1]}</strong><span>${details[2]}</span></div><p class="subtle">${details[3]}</p><div class="trainer-analytics"><div class="analytics-line"><span>06h</span><i style="--line-value:92%"></i></div><div class="analytics-line"><span>12h</span><i style="--line-value:67%"></i></div><div class="analytics-line"><span>18h</span><i style="--line-value:42%"></i></div><div class="analytics-line"><span>00h</span><i style="--line-value:31%"></i></div></div></div></div>`); bindClose(); }
function openAdminAudit() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Security and operations</div><h3>Audit trail</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="toolbar"><button class="filter active-filter" data-audit-filter="all">All events</button><button class="filter" data-audit-filter="today">Today</button><button class="filter" data-action="export-audit">Export CSV</button></div><table class="table audit-table"><tbody><tr data-audit-day="today"><td><strong>Program published</strong><br /><small>Maya Singh · 2 min ago</small></td><td>trainer</td><td><span class="pill">Success</span></td></tr><tr data-audit-day="today"><td><strong>Trainer invitation created</strong><br /><small>Admin · 18 min ago</small></td><td>admin</td><td><span class="pill">Success</span></td></tr><tr data-audit-day="older"><td><strong>Login challenge</strong><br /><small>Unknown device · yesterday</small></td><td>security</td><td><span class="pill coral">Reviewed</span></td></tr></tbody></table></div></div>`); bindClose(); document.querySelectorAll('[data-audit-filter]').forEach(filter => filter.addEventListener('click', () => { document.querySelectorAll('[data-audit-filter]').forEach(item => item.classList.remove('active-filter')); filter.classList.add('active-filter'); document.querySelectorAll('[data-audit-day]').forEach(row => { row.style.display = filter.dataset.auditFilter === 'all' || row.dataset.auditDay === filter.dataset.auditFilter ? 'table-row' : 'none'; }); })); document.querySelector('[data-action="export-audit"]').addEventListener('click', () => { const csv = 'event,actor,time,status\nProgram published,Maya Singh,2 min ago,Success\nTrainer invitation created,Admin,18 min ago,Success\nLogin challenge,Unknown device,yesterday,Reviewed'; const blob = new Blob([csv], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'elevate-audit-trail.csv'; link.click(); URL.revokeObjectURL(url); showToast('Audit CSV exported'); }); }
function openAdminResetWithTwoFactor() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Admin only · Two-factor verification</div><h3>Reset administrator password</h3></div><button class="ghost" data-action="close-modal">Close</button></div><p class="subtle">A verification code was sent to the admin authenticator. Demo code: <strong>246810</strong>.</p><form id="admin-reset-2fa"><div class="form-field"><label>Authenticator code</label><input name="code" inputmode="numeric" pattern="246810" placeholder="6 digits" required /></div><div class="form-field"><label>New temporary password</label><input type="password" value="Elevate-2026!" required /></div><button class="primary full" type="submit">Verify and reset password</button></form></div></div>`); bindClose(); document.querySelector('#admin-reset-2fa').addEventListener('submit', event => { event.preventDefault(); if (event.currentTarget.elements.code.value !== '246810') { showToast('Invalid authenticator code'); return; } event.currentTarget.closest('.modal-backdrop').remove(); showToast('Admin password reset completed'); }); }
function openClientReview(name, reason) {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Client pulse · ${reason}</div><h3>${name}</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="review-summary">${metric('Completion', name === 'Daniel Reed' ? '64%' : '92%', 'last 30 days')}${metric('Current goal', name === 'Daniel Reed' ? 'Fat loss' : 'Muscle gain', 'trainer assigned')}${metric('Last activity', name === 'Daniel Reed' ? '3 days ago' : '12 min ago', 'needs review')}</div><div class="review-section"><div class="panel-head"><div><div class="eyebrow">Workout history</div><h3>Review each session</h3></div><span class="subtle">Assigned to Maya Singh</span></div><div class="review-workout-row"><span>14 Sep · Lower body strength</span><strong>5 / 5 blocks</strong><button class="icon-button" data-action="review-workout-detail">Open workout</button></div><div class="review-workout-row"><span>12 Sep · Cardio rotation</span><strong>4 / 5 blocks</strong><button class="icon-button" data-action="review-workout-detail">Open workout</button></div><div class="review-workout-row"><span>10 Sep · HIIT</span><strong>4 / 4 rounds</strong><button class="icon-button" data-action="review-workout-detail">Open workout</button></div></div><div class="review-timeline"><div><strong>Today</strong><span>${reason === 'Missed session' ? 'Send a check-in about the missed workout.' : 'Review activity and leave a coaching note.'}</span></div><div><strong>Next action</strong><span>${reason === 'Meal log' ? 'Review food photo and portion details.' : 'Send a plan adjustment or check-in.'}</span></div></div><button class="primary full" data-action="send-coaching-note">Send coaching note</button></div></div>`);
  bindClose();
  document.querySelectorAll('[data-action="review-workout-detail"]').forEach(button => button.addEventListener('click', () => openWorkoutDetail('weights')));
  document.querySelector('[data-action="send-coaching-note"]').addEventListener('click', () => openCoachingComposer(name, reason));
}
function openCoachingComposer(name, reason) {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop coaching-layer" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Trainer message · ${name}</div><h3>Write a coaching note</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="message-presets"><button type="button" data-message-preset="Great work on today’s session. Keep the same control next time.">Great work</button><button type="button" data-message-preset="I noticed a gap in your session. Let’s adjust the plan together.">Needs check-in</button><button type="button" data-message-preset="Your meal log is received. I’ll review portions and reply shortly.">Meal feedback</button></div><form id="coaching-form"><div class="form-field"><label>Your message</label><textarea id="coaching-message" rows="6" required placeholder="Write a personal note for this client..."></textarea></div><label class="check dark-check"><input type="checkbox" checked /> Send as in-app notification</label><label class="check dark-check"><input type="checkbox" /> Also send by WhatsApp</label><button class="primary full" type="submit">Send custom message</button></form></div></div>`); bindClose(); document.querySelectorAll('[data-message-preset]').forEach(button => button.addEventListener('click', () => { document.querySelector('#coaching-message').value = button.dataset.messagePreset; })); document.querySelector('#coaching-form').addEventListener('submit', event => { event.preventDefault(); const message = document.querySelector('#coaching-message').value.trim(); event.currentTarget.closest('.modal-backdrop').remove(); showToast(`Custom coaching note sent to ${name}: ${message.slice(0, 42)}${message.length > 42 ? '…' : ''}`); });
}
function renderTrainer() {
  shell(`<section class="dashboard"><div class="dashboard-head"><div><div class="eyebrow">Monday, 14 September 2026</div><h1>Good morning, Maya.</h1></div><div class="dashboard-actions"><button class="ghost" data-action="review-queue">Review queue <span class="nav-count">7</span></button><button class="primary" data-action="create-program">Create program</button></div></div><div class="grid-4">${metric('Active clients', '24', '+3 this month')}${metric('Completion rate', '86%', '+8.4% vs last month')}${metric('Needs attention', '07', '2 urgent today')}${metric('Meal logs', '31', 'awaiting review')}</div><div class="content-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Client pulse</div><h3>Everyone, at a glance</h3></div><button class="ghost" data-action="view-all-clients">View all</button></div><div class="toolbar"><span class="filter">All goals</span><span class="filter">Needs attention</span><span class="filter">This week</span></div><table class="table"><thead><tr><th>Client</th><th>Last session</th><th>Goal</th><th>Status</th></tr></thead><tbody><tr><td><div class="person">${avatar('Aisha Khan')}<div><strong>Aisha Khan</strong><small>18 sessions</small></div></div></td><td>Today, 08:20</td><td>Muscle gain</td><td><span class="pill">On track</span></td></tr><tr><td><div class="person">${avatar('Daniel Reed')}<div><strong>Daniel Reed</strong><small>12 sessions</small></div></div></td><td>3 days ago</td><td>Fat loss</td><td><span class="pill coral">Review</span></td></tr><tr><td><div class="person">${avatar('Priya Shah')}<div><strong>Priya Shah</strong><small>22 sessions</small></div></div></td><td>Yesterday</td><td>Shredding</td><td><span class="pill">New log</span></td></tr></tbody></table></div><div class="panel"><div class="eyebrow">Attention queue</div><h3 style="margin-top:8px">Worth a look</h3><div class="attention"><div class="person">${avatar('Daniel Reed')}<div><strong>Daniel missed a session</strong><small>3 days ago</small></div></div><button class="icon-button" data-action="review-daniel">→</button></div><div class="attention"><div class="person">${avatar('Priya Shah')}<div><strong>Priya added a meal</strong><small>12 min ago</small></div></div><button class="icon-button" data-action="review-priya">→</button></div><div class="attention"><div class="person">${avatar('Laura Kim')}<div><strong>Laura needs a plan</strong><small>Tomorrow</small></div></div><button class="icon-button" data-action="review-laura">→</button></div></div></div></section>`, 'Trainer dashboard');
  document.querySelector('.dashboard').insertAdjacentHTML('afterbegin', `<div class="trainer-slot-board panel"><div class="panel-head"><div><div class="eyebrow">Today’s schedule</div><h3>Client training slots</h3></div><span class="pill">${slotNotification}</span></div><div class="slot-board-grid"><button class="slot-board-card" data-trainer-slot="Morning"><strong>Morning</strong><span>06:00–08:00 · 6 clients</span><small>Aisha, Omar, Priya + 3</small><b>Reschedule →</b></button><button class="slot-board-card" data-trainer-slot="Afternoon"><strong>Afternoon</strong><span>12:00–14:00 · 10 clients</span><small>Daniel, Laura + 8</small><b>Reschedule →</b></button><button class="slot-board-card" data-trainer-slot="Evening"><strong>Evening</strong><span>18:00–20:00 · 8 clients</span><small>4 slots open</small><b>Reschedule →</b></button></div></div>`);
  document.querySelectorAll('[data-trainer-slot]').forEach(button => button.addEventListener('click', () => openTrainerReschedule(button.dataset.trainerSlot)));
  document.querySelectorAll('.grid-4 .metric').forEach((card, index) => card.addEventListener('click', () => openTrainerMetric(['clients', 'completion', 'attention', 'meals'][index])));
  document.querySelector('[data-action="review-queue"]').addEventListener('click', openTrainerReviewQueue);
  document.querySelector('[data-action="create-program"]').addEventListener('click', () => { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Program builder</div><h3>Create a program</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="program-form"><div class="form-field"><label>Program name</label><input name="name" value="Foundation strength" /></div><div class="form-grid"><label class="form-field"><span>Type</span><select name="type"><option>Weights</option><option>Cardio</option><option>HIIT</option></select></label><label class="form-field"><span>Target goal</span><select name="goal"><option>Muscle gain</option><option>Fat loss</option><option>Shredding</option></select></label></div><div class="form-field"><label>Demo video</label><div class="upload-box">Drop a licensed video or paste a demo URL<br /><small>Demo placeholder ready</small></div></div><button class="primary full" type="submit">Save draft program</button></form></div></div>`); bindClose(); document.querySelector('#program-form').addEventListener('submit', event => { event.preventDefault(); event.currentTarget.closest('.modal-backdrop').remove(); showToast('Program draft saved'); }); });
  document.querySelector('[data-action="review-daniel"]').addEventListener('click', () => openClientReview('Daniel Reed', 'Missed session'));
  document.querySelector('[data-action="review-priya"]').addEventListener('click', () => openClientReview('Priya Shah', 'Meal log'));
  document.querySelector('[data-action="review-laura"]').addEventListener('click', () => openClientReview('Laura Kim', 'Plan needed'));
  document.querySelector('[data-action="view-all-clients"]').addEventListener('click', () => openClientReview('Client pulse', 'All 24 assigned clients'));
}
function openAccountCreator() {
  document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Account management</div><h3>Create a new account</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="account-form"><div class="segmented account-tabs"><button type="button" class="active" data-account-role="client">Client</button><button type="button" data-account-role="trainer">Trainer</button></div><div class="form-field"><label>Full name</label><input name="name" placeholder="Alex Morgan" required /></div><div class="form-field"><label>Email address</label><input name="email" type="email" placeholder="alex@example.com" required /></div><div class="form-field"><label>Temporary password</label><input name="password" value="Elevate-2026!" required /></div><div class="form-field"><label>Assigned trainer or gym</label><select name="assignment"><option>Maya Singh · Elevate Central</option><option>Unassigned / invite later</option></select></div><div class="form-field account-extra"><label>Client goal</label><select name="goal"><option>Fat loss</option><option>Muscle gain</option><option>Shredding</option></select></div><button class="primary full" type="submit">Create client account</button></form></div></div>`);
  document.querySelector('#account-form').insertAdjacentHTML('afterbegin', '<div class="photo-upload"><div class="avatar">?</div><div><strong>Profile picture</strong><small>Request or upload a clear client/trainer photo</small></div><button type="button" class="ghost">Choose photo</button></div>');
  bindClose();
  document.querySelectorAll('[data-account-role]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-account-role]').forEach(item => item.classList.remove('active')); button.classList.add('active'); const isClient = button.dataset.accountRole === 'client'; document.querySelector('.account-extra').style.display = isClient ? 'block' : 'none'; document.querySelector('#account-form button[type="submit"]').textContent = `Create ${isClient ? 'client' : 'trainer'} account`; }));
  document.querySelector('#account-form').addEventListener('submit', event => { event.preventDefault(); const role = document.querySelector('[data-account-role].active').dataset.accountRole; event.currentTarget.closest('.modal-backdrop').remove(); showToast(`${role === 'client' ? 'Client' : 'Trainer'} account created and credentials issued`); });
}
function renderAdmin() {
  shell(`<section class="dashboard"><div class="dashboard-head"><div><div class="eyebrow">Operations control</div><h1>Everything in rhythm.</h1></div><div class="dashboard-actions"><button class="ghost" data-action="audit">Audit trail</button><button class="primary" data-action="invite">Invite trainer</button></div></div><div class="grid-4">${metric('Active trainers', '42', '5 invitations pending')}${metric('Connected clients', '1,284', '+12% this month')}${metric('API p95', '182 ms', 'within budget')}${metric('Uptime', '99.98%', 'last 30 days')}</div><div class="content-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Platform health</div><h3>Live command center</h3></div><span class="pill">All systems go</span></div><div class="workout-list"><div class="workout-row"><div class="workout-icon">↗</div><div><strong>API response time</strong><small>p95 · 182 ms</small></div><span class="status">Healthy</span></div><div class="workout-row"><div class="workout-icon">◌</div><div><strong>Realtime connections</strong><small>1,284 active clients</small></div><span class="status">Healthy</span></div><div class="workout-row"><div class="workout-icon">↑</div><div><strong>Media processing</strong><small>14 items in queue</small></div><span class="status">Healthy</span></div></div></div><div class="panel"><div class="eyebrow">Platform activity</div><h3 style="margin-top:8px">Live pulse</h3><div class="attention"><div><strong>Workouts started</strong><small>Last 24 hours</small></div><strong>186</strong></div><div class="attention"><div><strong>Meal logs uploaded</strong><small>Last 24 hours</small></div><strong>94</strong></div><div class="attention"><div><strong>Trainer response rate</strong><small>This week</small></div><strong>92%</strong></div></div></div><div class="content-grid admin-lower"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Motivation</div><h3>Community leaderboard</h3></div><button class="ghost" data-action="leaderboard">Open board</button></div><div class="leader-row"><strong>01</strong>${avatar('Aisha Khan')}<span>Aisha Khan</span><b>18 sessions</b></div><div class="leader-row"><strong>02</strong>${avatar('Priya Shah')}<span>Priya Shah</span><b>16 sessions</b></div><div class="leader-row"><strong>03</strong>${avatar('Daniel Reed')}<span>Daniel Reed</span><b>12 sessions</b></div></div><div class="panel"><div class="panel-head"><div><div class="eyebrow">Content library</div><h3>Demo videos</h3></div><button class="primary" data-action="add-video">Add demo</button></div><p class="subtle">Admin and trainers can add licensed demonstrations or animated placeholders.</p><div class="upload-box">+ Add a form demo<br /><small>MP4, MOV, or approved video link</small></div></div></div></section>`, 'Admin console');
  const platformActivity = Array.from(document.querySelectorAll('.panel')).find(panel => panel.querySelector('h3')?.textContent === 'Live pulse');
  platformActivity?.querySelectorAll('.attention').forEach((row, index) => { row.classList.add('interactive-row'); row.dataset.action = ['platform-workouts', 'platform-meals', 'platform-response'][index]; });
  document.querySelector('.admin-lower').insertAdjacentHTML('beforebegin', '<div class="panel assignment-panel"><div class="panel-head"><div><div class="eyebrow">People directory</div><h3>Trainer and client assignments</h3></div><span class="pill">42 trainers · 1,284 clients</span></div><div class="assignment-row"><div class="person"><div class="avatar">AK</div><div><strong>Aisha Khan</strong><small>Client · Muscle gain · profile photo requested</small></div></div><span>Maya Singh</span><button class="icon-button" data-action="manage-aisha">Manage</button><button class="danger-button" data-action="delete-aisha">Delete</button></div><div class="assignment-row"><div class="person"><div class="avatar">DR</div><div><strong>Daniel Reed</strong><small>Client · Fat loss · profile photo received</small></div></div><span>Maya Singh</span><button class="icon-button" data-action="manage-daniel">Manage</button><button class="danger-button" data-action="delete-daniel">Delete</button></div><div class="assignment-row"><div class="person"><div class="avatar">MS</div><div><strong>Maya Singh</strong><small>Trainer · Elevate Central · 24 clients</small></div></div><span>Admin owner</span><button class="icon-button" data-action="manage-maya">Manage</button><button class="danger-button" data-action="delete-maya">Delete</button></div></div>');
  document.querySelector('.dashboard-actions').insertAdjacentHTML('afterbegin', '<button class="ghost" data-action="create-account">Create account</button>');
  document.querySelector('[data-action="create-account"]').addEventListener('click', openAccountCreator);
  document.querySelector('[data-action="audit"]').addEventListener('click', openAdminAudit);
  document.querySelector('[data-action="invite"]').addEventListener('click', openInvite);
  document.querySelector('[data-action="leaderboard"]').addEventListener('click', openLeaderboard);
  document.querySelector('[data-action="add-video"]').addEventListener('click', openVideo);
  document.querySelectorAll('[data-action^="manage-"]').forEach(button => button.addEventListener('click', () => openAdminManage(button.dataset.action.replace('manage-', '').replace('aisha', 'Aisha Khan').replace('daniel', 'Daniel Reed').replace('maya', 'Maya Singh'))));
  document.querySelectorAll('[data-action^="delete-"]').forEach(button => button.addEventListener('click', () => openAdminDelete(button.dataset.action.replace('delete-', '').replace('aisha', 'Aisha Khan').replace('daniel', 'Daniel Reed').replace('maya', 'Maya Singh'))));
  document.querySelectorAll('[data-action="platform-workouts"]').forEach(button => button.addEventListener('click', () => openPlatformActivity('workouts')));
  document.querySelectorAll('[data-action="platform-meals"]').forEach(button => button.addEventListener('click', () => openPlatformActivity('meals')));
  document.querySelectorAll('[data-action="platform-response"]').forEach(button => button.addEventListener('click', () => openPlatformActivity('response')));
}
function openAudit() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal wide" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Security and operations</div><h3>Audit trail</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="toolbar"><span class="filter">All events</span><span class="filter">Today</span><span class="filter">Export CSV</span></div><table class="table"><tbody><tr><td><strong>Program published</strong><br /><small>Maya Singh · 2 min ago</small></td><td>trainer</td><td><span class="pill">Success</span></td></tr><tr><td><strong>Trainer invitation created</strong><br /><small>Admin · 18 min ago</small></td><td>admin</td><td><span class="pill">Success</span></td></tr><tr><td><strong>Login challenge</strong><br /><small>Unknown device · 1 hr ago</small></td><td>security</td><td><span class="pill coral">Reviewed</span></td></tr></tbody></table></div></div>`); bindClose(); }
function openInvite() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Trainer access</div><h3>Add trainer credentials</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="invite-form"><div class="form-field"><label>Trainer name</label><input name="name" placeholder="Maya Singh" required /></div><div class="form-field"><label>Email address</label><input name="email" type="email" placeholder="maya@gym.com" required /></div><div class="form-field"><label>Temporary password</label><input name="password" value="Elevate-2026!" required /></div><div class="form-field"><label>Gym / tenant</label><select><option>Elevate Central</option><option>Elevate North</option></select></div><button class="primary full" type="submit">Create credentials and invite</button></form></div></div>`); document.querySelector('#invite-form').insertAdjacentHTML('afterbegin', '<div class="photo-upload"><div class="avatar">?</div><div><strong>Profile picture</strong><small>Request a trainer photo</small></div><button type="button" class="ghost">Choose photo</button></div>'); bindClose(); document.querySelector('#invite-form').addEventListener('submit', event => { event.preventDefault(); event.currentTarget.closest('.modal-backdrop').remove(); showToast('Trainer credentials created and invitation sent'); }); }
function openLeaderboard() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Community motivation</div><h3>Monthly leaderboard</h3></div><button class="ghost" data-action="close-modal">Close</button></div><div class="leader-row top"><strong>01</strong>${avatar('Aisha Khan')}<span>Aisha Khan</span><b>18 sessions · 6 day streak</b></div><div class="leader-row"><strong>02</strong>${avatar('Priya Shah')}<span>Priya Shah</span><b>16 sessions · 4 day streak</b></div><div class="leader-row"><strong>03</strong>${avatar('Daniel Reed')}<span>Daniel Reed</span><b>12 sessions · 3 day streak</b></div></div></div>`); bindClose(); }
function openVideo() { document.querySelector('.app-shell').insertAdjacentHTML('beforeend', `<div class="modal-backdrop" data-action="close-modal"><div class="modal" role="dialog" onclick="event.stopPropagation()"><div class="panel-head"><div><div class="eyebrow">Content library</div><h3>Add a demo video</h3></div><button class="ghost" data-action="close-modal">Close</button></div><form id="video-form"><div class="form-field"><label>Exercise name</label><input name="exercise" placeholder="Goblet squat" required /></div><div class="form-field"><label>Video URL or upload placeholder</label><input placeholder="https://youtube.com/..." /></div><div class="upload-box animated-demo">Animated preview placeholder</div><button class="primary full" type="submit">Add to demo library</button></form></div></div>`); bindClose(); document.querySelector('#video-form').addEventListener('submit', event => { event.preventDefault(); event.currentTarget.closest('.modal-backdrop').remove(); showToast('Demo added to the content library'); }); }
function renderDashboard(role) { role === 'client' ? renderClient() : role === 'trainer' ? renderTrainer() : renderAdmin(); }
function formatTime(seconds) { return `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`; }
function renderRuntime() {
  const workout = workoutData[selectedWorkoutType];
  const selection = `<div class="panel selection-panel"><div class="panel-head"><div><div class="eyebrow">Phase 03 / 04</div><h3>Choose today’s workout</h3></div><span class="pill">Trainer assigned</span></div><div class="workout-types">${[['cardio', 'Cardio', '60 min · 3 sets', '◒'], ['weights', 'Weight lifting', '45 min · sets + targets', '◈'], ['hiit', 'HIIT', '18 min · intervals', '⚡']].map(type => `<button class="type-card ${type[0] === selectedWorkoutType ? 'selected' : ''}" data-workout-type="${type[0]}"><span class="type-symbol ${type[0] === 'weights' ? 'weights-symbol' : ''}">${type[3]}</span><strong>${type[1]}</strong><small>${type[2]}</small></button>`).join('')}</div>${selectedWorkoutType === 'weights' ? `<div class="muscle-picker"><div class="picker-head"><strong>Target muscle focus</strong><div class="segmented"><button class="${selectedMuscleMode === 'single' ? 'active' : ''}" data-muscle-mode="single">Single muscle</button><button class="${selectedMuscleMode === 'double' ? 'active' : ''}" data-muscle-mode="double">Double muscle</button></div></div>${selectedMuscleMode === 'double' ? '<div class="recommended-pair"><strong>Trainer recommendation</strong><span>Back + Biceps · balanced pull day</span><button class="ghost" data-action="use-recommended-pair">Use recommendation</button></div>' : ''}<div class="muscle-options">${['Legs', 'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps'].map(muscle => `<button class="muscle-chip ${selectedMuscles.includes(muscle) ? 'chosen' : ''}" data-muscle="${muscle}">${muscle}</button>`).join('')}</div><small class="subtle">${selectedMuscles.join(' + ')} selected · program adjusts to ${profile.goal.toLowerCase()}</small></div>` : ''}<div class="runtime-actions"><button class="dark-button" data-action="open-demo">View ${workout.title} demo</button></div></div>`;
  const totalBlocks = workout.blocks.length;
  const demo = `<div class="panel demo-panel"><div class="panel-head"><div><div class="eyebrow">Phase 03 / 04 · ${selectedWorkoutType.toUpperCase()}</div><h3>${workout.title}</h3><p class="subtle">${workout.subtitle}</p></div><button class="ghost" data-action="back-select">Change</button></div><div class="demo-visual"><button class="play-button" data-action="play-demo" aria-label="Play ${workout.demo} demonstration">▶</button><div><span>FORM DEMO</span><strong>${workout.demo}</strong><small>${workout.cue}</small></div></div><div class="set-progress"><div class="progress-label"><strong>Workout progress</strong><span>${completedSets} / ${totalBlocks} blocks complete</span></div><div class="bar"><i style="width:${Math.min(completedSets / totalBlocks * 100, 100)}%"></i></div></div><div class="workout-list">${workout.blocks.map((block, index) => `<div class="workout-row"><div class="workout-icon">${String(index + 1).padStart(2, '0')}</div><div><strong>${block}</strong><small>${index < completedSets ? 'Block complete' : 'Complete this block to continue'}</small></div><button class="mini-button ${index < completedSets ? 'done' : ''}" data-complete-set="${index}">${index < completedSets ? 'Done' : 'Complete'}</button></div>`).join('')}</div><div class="runtime-actions"><button class="dark-button" data-action="complete-session">Complete workout</button></div></div>`;
  const recovery = `<div class="panel recovery-panel"><div class="eyebrow">Phase 04 / 04</div><h3>Strong work, Aisha.</h3><p class="subtle">Bring your heart rate down with your trainer’s recommended recovery.</p><div class="recovery-callout"><strong>Post-workout cardio</strong><span>8 min · easy incline walk</span></div><div class="recovery-callout"><strong>Guided stretch</strong><span>Cat-cow · hip flexor · hamstring · 08:00</span></div><div class="runtime-actions"><button class="primary" data-action="finish-session">Finish session</button></div></div>`;
  const warmup = `<div class="runtime-stage"><div class="phase"><span>PHASE 01 / 04</span><span>Warm-up</span></div><div class="timer">${formatTime(timerSeconds)}</div><div class="stage-bottom"><div><h2>Warm-up flow</h2><p>Prepare your body. Let the session come to you.</p></div><button class="primary" data-action="toggle-timer">${timerRunning ? 'Pause timer' : 'Start timer'}</button></div></div><div class="panel checklist"><div class="panel-head"><div><div class="eyebrow">Phase 02 / 04 · Before you begin</div><h3>Pre-workout check</h3></div><span class="pill">3 min</span></div>${['Hydration ready', 'L-carnitine reminder', 'Pre-workout supplement', 'Creatine · due in 18 min', 'Trainer-defined items'].map(item => `<label class="check"><input type="checkbox" /> ${item}</label>`).join('')}<div class="runtime-actions"><button class="dark-button" data-action="next-step">Continue to workout selection</button></div></div>`;
  const stage = runtimeStep === 'warmup' ? warmup : runtimeStep === 'selection' ? selection : runtimeStep === 'demo' ? demo : recovery;
  shell(`<section class="runtime"><div class="runtime-top"><div><div class="eyebrow">Monday · Today’s session</div><h1>Find your rhythm.</h1></div><button class="ghost" data-action="back-dashboard">Exit</button></div>${stage}</section>`, 'Active session');
  document.querySelector('[data-action="back-dashboard"]').addEventListener('click', () => { timerRunning = false; clearInterval(timerId); renderClient(); });
  document.querySelector('[data-action="toggle-timer"]')?.addEventListener('click', () => { timerRunning = !timerRunning; clearInterval(timerId); if (timerRunning) timerId = setInterval(() => { timerSeconds = Math.max(timerSeconds - 1, 0); renderRuntime(); }, 1000); renderRuntime(); });
  document.querySelector('[data-action="next-step"]')?.addEventListener('click', () => { timerRunning = false; clearInterval(timerId); runtimeStep = 'selection'; renderRuntime(); });
  document.querySelectorAll('[data-workout-type]').forEach(button => button.addEventListener('click', () => { selectedWorkoutType = button.dataset.workoutType; completedSets = 0; renderRuntime(); }));
  document.querySelectorAll('[data-muscle-mode]').forEach(button => button.addEventListener('click', () => { selectedMuscleMode = button.dataset.muscleMode; selectedMuscles = selectedMuscleMode === 'single' ? [selectedMuscles[0] || 'Legs'] : [...new Set([...selectedMuscles, 'Back'])].slice(0, 2); renderRuntime(); }));
  document.querySelector('[data-action="use-recommended-pair"]')?.addEventListener('click', () => { selectedMuscleMode = 'double'; selectedMuscles = ['Back', 'Biceps']; renderRuntime(); showToast('Recommended Back + Biceps pairing selected'); });
  document.querySelectorAll('[data-muscle]').forEach(button => button.addEventListener('click', () => { const muscle = button.dataset.muscle; if (selectedMuscleMode === 'single') selectedMuscles = [muscle]; else if (selectedMuscles.includes(muscle)) selectedMuscles = selectedMuscles.filter(item => item !== muscle); else if (selectedMuscles.length < 2) selectedMuscles.push(muscle); renderRuntime(); }));
  document.querySelector('[data-action="open-demo"]')?.addEventListener('click', () => { runtimeStep = 'demo'; renderRuntime(); });
  document.querySelector('[data-action="play-demo"]')?.addEventListener('click', event => { event.currentTarget.textContent = 'Ⅱ'; event.currentTarget.classList.add('playing'); showToast(`${workout.demo} demo playing`); });
  document.querySelectorAll('[data-complete-set]').forEach(button => button.addEventListener('click', () => { const index = Number(button.dataset.completeSet); if (index === completedSets) { completedSets += 1; showToast(`Set ${completedSets} complete`); renderRuntime(); } }));
  document.querySelector('[data-action="back-select"]')?.addEventListener('click', () => { runtimeStep = 'selection'; renderRuntime(); });
  document.querySelector('[data-action="complete-session"]')?.addEventListener('click', () => { completedSets = workout.blocks.length; runtimeStep = 'recovery'; renderRuntime(); });
  document.querySelector('[data-action="finish-session"]')?.addEventListener('click', () => { timerRunning = false; clearInterval(timerId); lastCompletion = { type: selectedWorkoutType, ...calculateCompletion(selectedWorkoutType) }; runtimeStep = 'warmup'; renderCompletionSummary(); });
}
renderLogin();
