const app = document.querySelector('#app');
const roles = ['client', 'trainer', 'admin'];
let selectedRole = 'client';
let timerSeconds = 1122;
let timerRunning = false;
let timerId;
let runtimeStep = 'warmup';
let selectedWorkoutType = 'weights';

const roleMeta = {
  client: { label: 'Client', title: 'Your strongest hour starts here.', description: 'A focused training companion, built around the plan your trainer made for you.', accent: 'Today, fully yours.' },
  trainer: { label: 'Trainer', title: 'Make every client feel seen.', description: 'One calm command center for plans, progress, and the moments that move clients forward.', accent: 'Coach with clarity.' },
  admin: { label: 'Admin', title: 'The quiet power behind the platform.', description: 'See the health of your operation at a glance and keep every trainer moving.', accent: 'Operations, elevated.' }
};

function shell(content, action = '') {
  app.innerHTML = `<div class="app-shell"><header class="topbar"><div class="brand"><span class="brand-mark">E</span> ELEVATE</div><div class="top-actions"><span class="eyebrow">${action || 'Personal training, refined'}</span>${action ? '<button class="ghost" data-action="logout">Sign out</button>' : ''}</div></header><main class="main">${content}</main></div>`;
  document.querySelector('[data-action="logout"]')?.addEventListener('click', renderLogin);
}

function renderLogin() {
  shell(`<section class="login-layout"><div class="visual"><div><div class="eyebrow" style="color:#d5f34a">${roleMeta[selectedRole].accent}</div><h1>${roleMeta[selectedRole].title}</h1><p>${roleMeta[selectedRole].description}</p></div><div class="visual-foot"><div class="stat-chip"><strong>24/7</strong><span>trainer support</span></div><div class="stat-chip"><strong>01</strong><span>beautiful plan</span></div></div></div><div class="auth-card"><div class="eyebrow">${roleMeta[selectedRole].label} access</div><h2>Welcome back.</h2><p class="subtle">Sign in to continue your Elevate experience.</p><div class="role-tabs">${roles.map(role => `<button class="role-tab ${role === selectedRole ? 'active' : ''}" data-role="${role}">${roleMeta[role].label}</button>`).join('')}</div><form id="login-form"><div class="form-field"><label for="email">Email address</label><input id="email" type="email" value="${selectedRole}@elevate.demo" required /></div><div class="form-field"><label for="password">Password</label><input id="password" type="password" value="elevate-demo" required /></div><button class="primary full" type="submit">Continue securely</button></form><p class="demo-note">Demo mode is active. Use the prefilled credentials to explore this role.</p></div></section>`);
  document.querySelectorAll('[data-role]').forEach(button => button.addEventListener('click', () => { selectedRole = button.dataset.role; renderLogin(); }));
  document.querySelector('#login-form').addEventListener('submit', event => { event.preventDefault(); renderDashboard(selectedRole); });
}

function metric(label, value, note) { return `<div class="metric"><span>${label}</span><strong>${value}</strong><span>${note}</span></div>`; }
function avatar(name, tone = '') { return `<div class="avatar ${tone}">${name.split(' ').map(word => word[0]).join('').slice(0, 2)}</div>`; }

function renderClient() {
  shell(`<section class="dashboard"><div class="dashboard-head"><div><div class="eyebrow">Monday, 14 September 2026</div><h1>Good morning, Aisha.</h1></div><div class="dashboard-actions"><button class="ghost">Progress</button><button class="primary" data-action="start-workout">Start workout</button></div></div><div class="grid-4">${metric('Current weight', '68.4 kg', '-4.6 kg since start')}${metric('BMI', '21.6', 'within your target range')}${metric('Sessions complete', '18 / 24', '75% this month')}${metric('Streak', '06 days', 'your best yet')}</div><div class="content-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Your plan</div><h3>Today’s session</h3></div><span class="pill">Ready</span></div><div class="workout-list"><div class="workout-row"><div class="workout-icon">01</div><div><strong>Warm-up flow</strong><small>20 min · guided timer</small></div><span class="status">Next</span></div><div class="workout-row"><div class="workout-icon">02</div><div><strong>Lower body strength</strong><small>45 min · 6 exercises</small></div><span class="status">Assigned</span></div><div class="workout-row"><div class="workout-icon">03</div><div><strong>Recovery stretch</strong><small>08 min · guided cues</small></div><span class="status">After</span></div></div></div><div class="panel"><div class="eyebrow">This month</div><div class="progress-ring"><div class="progress-copy"><strong>72%</strong><span>complete</span></div></div><p class="subtle" style="text-align:center">Three sessions away from your monthly target.</p></div></div><div class="panel schedule-panel"><div class="panel-head"><div><div class="eyebrow">Your week</div><h3>Training schedule</h3></div><span class="subtle">14–20 Sep</span></div><div class="schedule"><div class="schedule-day active"><span>MON</span><strong>14</strong><small>Strength</small></div><div class="schedule-day"><span>TUE</span><strong>15</strong><small>Cardio</small></div><div class="schedule-day"><span>WED</span><strong>16</strong><small>Rest</small></div><div class="schedule-day"><span>THU</span><strong>17</strong><small>HIIT</small></div><div class="schedule-day"><span>FRI</span><strong>18</strong><small>Strength</small></div><div class="schedule-day"><span>SAT</span><strong>19</strong><small>Recovery</small></div><div class="schedule-day"><span>SUN</span><strong>20</strong><small>Rest</small></div></div></div></section>`, 'Client dashboard');
  document.querySelector('[data-action="start-workout"]').addEventListener('click', renderRuntime);
}

function renderTrainer() {
  shell(`<section class="dashboard"><div class="dashboard-head"><div><div class="eyebrow">Monday, 14 September 2026</div><h1>Good morning, Maya.</h1></div><div class="dashboard-actions"><button class="ghost">Review queue</button><button class="primary">Create program</button></div></div><div class="grid-4">${metric('Active clients', '24', '+3 this month')}${metric('Completion rate', '86%', '+8.4% vs last month')}${metric('Needs attention', '07', '2 urgent today')}${metric('Meal logs', '31', 'awaiting review')}</div><div class="content-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Client pulse</div><h3>Everyone, at a glance</h3></div><button class="ghost">View all</button></div><div class="toolbar"><span class="filter">All goals</span><span class="filter">Needs attention</span><span class="filter">This week</span></div><table class="table"><thead><tr><th>Client</th><th>Last session</th><th>Goal</th><th>Status</th></tr></thead><tbody><tr><td><div class="person">${avatar('Aisha Khan')}<div><strong>Aisha Khan</strong><small>18 sessions</small></div></div></td><td>Today, 08:20</td><td>Muscle gain</td><td><span class="pill">On track</span></td></tr><tr><td><div class="person">${avatar('Daniel Reed')}<div><strong>Daniel Reed</strong><small>12 sessions</small></div></div></td><td>3 days ago</td><td>Fat loss</td><td><span class="pill coral">Review</span></td></tr><tr><td><div class="person">${avatar('Priya Shah')}<div><strong>Priya Shah</strong><small>22 sessions</small></div></div></td><td>Yesterday</td><td>Shredding</td><td><span class="pill">New log</span></td></tr></tbody></table></div><div class="panel"><div class="eyebrow">Attention queue</div><h3 style="margin-top:8px">Worth a look</h3><div class="attention"><div class="person">${avatar('DR')}<div><strong>Daniel missed a session</strong><small>3 days ago</small></div></div><span>→</span></div><div class="attention"><div class="person">${avatar('PS')}<div><strong>Priya added a meal</strong><small>12 min ago</small></div></div><span>→</span></div><div class="attention"><div class="person">${avatar('LK')}<div><strong>Laura needs a plan</strong><small>Tomorrow</small></div></div><span>→</span></div></div></div></section>`, 'Trainer dashboard');
}

function renderAdmin() {
  shell(`<section class="dashboard"><div class="dashboard-head"><div><div class="eyebrow">Operations control</div><h1>Everything in rhythm.</h1></div><div class="dashboard-actions"><button class="ghost">Audit trail</button><button class="primary">Invite trainer</button></div></div><div class="grid-4">${metric('Active trainers', '42', '5 invitations pending')}${metric('Connected clients', '1,284', '+12% this month')}${metric('API p95', '182 ms', 'within budget')}${metric('Uptime', '99.98%', 'last 30 days')}</div><div class="content-grid"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Platform health</div><h3>Quietly operational</h3></div><span class="pill">All systems go</span></div><div class="workout-list"><div class="workout-row"><div class="workout-icon">↗</div><div><strong>API response time</strong><small>p95 · 182 ms</small></div><span class="status">Healthy</span></div><div class="workout-row"><div class="workout-icon">◌</div><div><strong>Realtime connections</strong><small>1,284 active clients</small></div><span class="status">Healthy</span></div><div class="workout-row"><div class="workout-icon">↑</div><div><strong>Media processing</strong><small>14 items in queue</small></div><span class="status">Healthy</span></div></div></div><div class="panel"><div class="eyebrow">Recent activity</div><h3 style="margin-top:8px">The latest</h3><div class="attention"><div><strong>Trainer invited</strong><small class="subtle"> · 2 min ago</small></div><span>MJ</span></div><div class="attention"><div><strong>Program published</strong><small class="subtle"> · 18 min ago</small></div><span>MS</span></div><div class="attention"><div><strong>Login challenged</strong><small class="subtle"> · 1 hr ago</small></div><span>OP</span></div></div></div></section>`, 'Admin console');
}

function renderDashboard(role) { role === 'client' ? renderClient() : role === 'trainer' ? renderTrainer() : renderAdmin(); }
function formatTime(seconds) { const minutes = Math.floor(seconds / 60).toString().padStart(2, '0'); const remainder = (seconds % 60).toString().padStart(2, '0'); return `${minutes}:${remainder}`; }
function renderRuntime() {
  const workout = { cardio: { title: 'Cardio rotation', subtitle: '60 min · 3 sets · guided intensity', demo: 'Treadmill incline walk', cue: 'Tall posture · light grip · steady breathing', blocks: ['Cross trainer · 15:00', 'Treadmill · 15:00', 'Air bike · 15:00', 'Spin bike · 15:00', 'Ski machine · 02:00'] }, weights: { title: 'Lower body strength', subtitle: '45 min · heavy to light progression', demo: 'Goblet squat', cue: 'Chest lifted · knees track over toes · controlled descent', blocks: ['Goblet squat · 3 × 8', 'Romanian deadlift · 3 × 10', 'Reverse lunge · 3 × 12'] }, hiit: { title: 'Athletic HIIT', subtitle: '18 min · 4 rounds · 30 / 30 intervals', demo: 'Battle rope waves', cue: 'Soft knees · fast hands · breathe continuously', blocks: ['Battle rope · 30 sec work', 'Step-up · 40 sec work', 'Rest · 60 sec'] } }[selectedWorkoutType];
  const selection = `<div class="panel selection-panel"><div class="panel-head"><div><div class="eyebrow">Phase 03 / 04</div><h3>Choose today’s workout</h3></div><span class="pill">Trainer assigned</span></div><div class="workout-types">${[['cardio', 'Cardio', '60 min · 3 sets', '↗'], ['weights', 'Weight lifting', '45 min · 6 exercises', '↓'], ['hiit', 'HIIT', '18 min · intervals', '⚡']].map(type => `<button class="type-card ${type[0] === selectedWorkoutType ? 'selected' : ''}" data-workout-type="${type[0]}"><span class="type-symbol">${type[3]}</span><strong>${type[1]}</strong><small>${type[2]}</small></button>`).join('')}</div><div class="runtime-actions"><button class="dark-button" data-action="open-demo">View ${workout.title} demo</button></div></div>`;
  const demo = `<div class="panel demo-panel"><div class="panel-head"><div><div class="eyebrow">Phase 03 / 04 · ${selectedWorkoutType.toUpperCase()}</div><h3>${workout.title}</h3><p class="subtle">${workout.subtitle}</p></div><button class="ghost" data-action="back-select">Change</button></div><div class="demo-visual"><button class="play-button" data-action="play-demo" aria-label="Play ${workout.demo} demonstration">▶</button><div><span>FORM DEMO</span><strong>${workout.demo}</strong><small>${workout.cue}</small></div></div><div class="workout-list">${workout.blocks.map((block, index) => `<div class="workout-row"><div class="workout-icon">0${index + 1}</div><div><strong>${block}</strong><small>Demonstration available</small></div><span class="status">Ready</span></div>`).join('')}</div><div class="runtime-actions"><button class="dark-button" data-action="complete-session">Complete workout</button></div></div>`;
  const recovery = `<div class="panel recovery-panel"><div class="eyebrow">Phase 04 / 04</div><h3>Strong work, Aisha.</h3><p class="subtle">Bring your heart rate down with your trainer’s recommended recovery.</p><div class="recovery-callout"><strong>Post-workout cardio</strong><span>8 min · easy incline walk</span></div><div class="recovery-callout"><strong>Guided stretch</strong><span>Cat-cow · hip flexor · hamstring · 08:00</span></div><div class="runtime-actions"><button class="primary" data-action="finish-session">Finish session</button></div></div>`;
  const stage = runtimeStep === 'warmup' ? `<div class="runtime-stage"><div class="phase"><span>PHASE 01 / 04</span><span>Warm-up</span></div><div class="timer">${formatTime(timerSeconds)}</div><div class="stage-bottom"><div><h2>Warm-up flow</h2><p>Prepare your body. Let the session come to you.</p></div><button class="primary" data-action="toggle-timer">${timerRunning ? 'Pause timer' : 'Start timer'}</button></div></div><div class="panel checklist"><div class="panel-head"><div><div class="eyebrow">Phase 02 / 04 · Before you begin</div><h3>Pre-workout check</h3></div><span class="pill">3 min</span></div><label class="check"><input type="checkbox" /> Hydration ready</label><label class="check"><input type="checkbox" /> L-carnitine reminder</label><label class="check"><input type="checkbox" /> Pre-workout supplement</label><label class="check"><input type="checkbox" /> Creatine · due in 18 min</label><label class="check"><input type="checkbox" /> Trainer-defined items</label><div class="runtime-actions"><button class="dark-button" data-action="next-step">Continue to workout selection</button></div></div>` : runtimeStep === 'selection' ? selection : runtimeStep === 'demo' ? demo : recovery;
  shell(`<section class="runtime"><div class="runtime-top"><div><div class="eyebrow">Monday · Today’s session</div><h1>Find your rhythm.</h1></div><button class="ghost" data-action="back-dashboard">Exit</button></div>${stage}</section>`, 'Active session');
  document.querySelector('[data-action="back-dashboard"]').addEventListener('click', renderClient);
  document.querySelector('[data-action="toggle-timer"]')?.addEventListener('click', () => { timerRunning = !timerRunning; clearInterval(timerId); if (timerRunning) timerId = setInterval(() => { timerSeconds = Math.max(timerSeconds - 1, 0); renderRuntime(); }, 1000); renderRuntime(); });
  document.querySelector('[data-action="next-step"]')?.addEventListener('click', () => { timerRunning = false; clearInterval(timerId); runtimeStep = 'selection'; renderRuntime(); });
  document.querySelectorAll('[data-workout-type]').forEach(button => button.addEventListener('click', () => { selectedWorkoutType = button.dataset.workoutType; renderRuntime(); }));
  document.querySelector('[data-action="open-demo"]')?.addEventListener('click', () => { runtimeStep = 'demo'; renderRuntime(); });
  document.querySelector('[data-action="play-demo"]')?.addEventListener('click', event => { event.currentTarget.textContent = 'Ⅱ'; event.currentTarget.classList.add('playing'); showToast(`${workout.demo} demo playing`); });
  document.querySelector('[data-action="back-select"]')?.addEventListener('click', () => { runtimeStep = 'selection'; renderRuntime(); });
  document.querySelector('[data-action="complete-session"]')?.addEventListener('click', () => { runtimeStep = 'recovery'; renderRuntime(); });
  document.querySelector('[data-action="finish-session"]')?.addEventListener('click', () => { runtimeStep = 'warmup'; timerSeconds = 1122; showToast('Session complete. Recovery logged.'); renderClient(); });
}
function showToast(message) { const toast = document.createElement('div'); toast.className = 'toast'; toast.textContent = message; document.body.appendChild(toast); setTimeout(() => toast.remove(), 2800); }
renderLogin();
